# <Button>:
#     #size_hint: 0.3, 0.5
#     height: 10
#     font_size:20
#     color:0.3,0.6,0.7,1
<MyGrid>:
    spacing:30
    canvas:
        Color:
            rgb:1,1,1
        Rectangle:
            size:self.size
            pos: self.pos

    # qr_label: QrRead

    BoxLayout:
        size_hint: 0.1,0.2
        canvas:
            Color:
                rgb:1,0,05, 0.5
        canvas:
            Rectangle:
                size: self.size
                pos: self.pos
        
        Button:
            text: "Read QR"
            #size_hint: None, None
            #size: 200, 50
            

    # BoxLayout:
    #     orientation: "vertical"
    #     size_hint: 1,1
    #     canvas:
    #         Color:
    #             rgb:0,0,1
    #         Rectangle:
    #             size: self.size
    #             pos: self.pos
            
        # BoxLayout:
        #     size_hint: 1,1
        #     canvas:
        #         Color:
        #             rgb:1,1,1,.5
        #         Rectangle:
        #             size: self.size
        #             pos: self.pos


    # GridLayout:
    #     color:1,0,0,0
    #     id: principal
    #     cols:2
    #     size: root.width - 100, root.height - 100
    #     pos: 50, 50


    #     GridLayout:
    #         BoxLayout:
    #             orientation:'vertical'
    #             padding: 15
    #         #pos: 300, 300
    #         #cols:1
    #             Button:
    #                 text:"Read QR Code"
    #                 #size_hint: None, None
    #                 #width: 300
    #                 #height: 70
    #                 #pos_hint: 1, 1
    #                 on_press:root.btn()
    #             Label:
    #                 text:"Reading.."
    #                 #size_hint:0.2, 0.2

    #             TextInput:
    #                 id:QrRead
    #                 multiline:False
    #                 size_hint:0.2, 0.2


    #     GridLayout:
    #         padding: 5
    #         size: root.width-200, root.width-200
    #         cols:3

    #         Label:
    #             text:"Name: "

    #         TextInput:
    #             multiline: False

